version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: cimg/python:3.11.1
  docker-terraform:
    docker:
      - image: hashicorp/terraform:1.0.11
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-plan:
    description: "Initializes and run plan from terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: plan
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform plan -out=plan.out
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
            - project/*
  terraform-compliance:
    description: "Run Terraform Compliance checks"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
            apk add --update --no-cache g++ gcc libxslt-dev python3-dev
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip install terraform-compliance
            terraform-compliance -f terraform-compliance/ -p plan.out
          name: terraform compliance
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-apply:
    description: "Runs Terraform Apply"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: apply
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve plan.out
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-lambda:
    description: "Deploys API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./HousingSearchApi/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./HousingSearchApi/
            npm i serverless-associate-waf
            npm i @serverless/safeguards-plugin --save-dev
            sls deploy --stage <<parameters.stage>> --conceal

jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check
  
  build-and-test:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build tests
          command: docker compose build housing-search-api-test;
      - run:
          name: Run tests
          command: docker compose run housing-search-api-test;
  build-and-test-v2:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build tests
          command: docker compose build housing-search-api-test-v2;
      - run:
          name: Run tests
          command: docker compose run housing-search-api-test-v2;
  assume-role-development:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DEVELOPMENT
  assume-role-staging:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION
  terraform-init-and-plan-development:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "development"
  terraform-compliance-development:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "development"
  terraform-apply-development:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "development"
  terraform-init-and-plan-staging:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "staging"
  terraform-compliance-staging:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "staging"
  terraform-apply-staging:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "staging"
  terraform-init-and-plan-production:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "production"
  terraform-compliance-production:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "production"
  terraform-apply-production:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "production"
  deploy-to-development:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "development"
  deploy-to-staging:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "staging"
  deploy-to-production:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"
  assume-role-pre-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRE_PRODUCTION
  terraform-init-and-plan-pre-production:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "pre-production"
  terraform-compliance-pre-production:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "pre-production"
  terraform-apply-pre-production:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "pre-production"
  deploy-to-pre-production:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "pre-production"

workflows:
  # check:
  #   jobs:
  #     - check-code-formatting:
  #         context: api-nuget-token-context
  #         filters:
  #           branches:
  #             ignore:
  #               - master
  #               - release
  #     - build-and-test:
  #         context:
  #           - api-nuget-token-context
  #           - SonarCloud
  #         filters:
  #           branches:
  #             ignore:
  #               - master
  #               - release
  #     - build-and-test-v2:
  #         context:
  #           - api-nuget-token-context
  #           - SonarCloud
  #         filters:
  #           branches:
  #             ignore:
  #               - master
  #               - release

  # check-and-deploy-development:
  #   jobs:
  #     - check-code-formatting:
  #         context: api-nuget-token-context
  #         filters:
  #             branches:
  #               only: master
  #     - build-and-test:
  #         context:
  #           - api-nuget-token-context
  #           - SonarCloud
  #         filters:
  #             branches:
  #               only: master
  #     - build-and-test-v2:
  #         context:
  #           - api-nuget-token-context
  #           - SonarCloud
  #         filters:
  #           branches:
  #             only: master
  #     - assume-role-development:
  #         context: api-assume-role-housing-development-context
  #         requires:
  #          - build-and-test
  #          - build-and-test-v2
  #         filters:
  #             branches:
  #               only: master
  #     - terraform-init-and-plan-development:
  #         requires:
  #           - assume-role-development
  #     - terraform-compliance-development:
  #         requires:
  #           - terraform-init-and-plan-development
  #     - terraform-apply-development:
  #         requires:
  #           - terraform-compliance-development
  #     - deploy-to-development:
  #         context:
  #           - api-nuget-token-context
  #           - "Serverless Framework"
  #         requires:
  #           - terraform-apply-development
  #         filters:
  #           branches:
  #             only: master
  # check-and-deploy-staging-and-production:
  #     jobs:
  #     - check-code-formatting:
  #         context: api-nuget-token-context
  #         filters:
  #           branches:
  #             only: release
  #     - build-and-test:
  #         context:
  #           - api-nuget-token-context
  #           - SonarCloud
  #         filters:
  #           branches:
  #             only: release
  #     - build-and-test-v2:
  #         context:
  #           - api-nuget-token-context
  #           - SonarCloud
  #         filters:
  #           branches:
  #             only: release
  #     - assume-role-staging:
  #         context: api-assume-role-housing-staging-context
  #         requires:
  #             - build-and-test
  #             - build-and-test-v2
  #         filters:
  #            branches:
  #              only: release
  #     - terraform-init-and-plan-staging:
  #         requires:
  #           - assume-role-staging
  #         filters:
  #           branches:
  #             only: release
  #     - terraform-compliance-staging:
  #         requires:
  #           - terraform-init-and-plan-staging
  #         filters:
  #           branches:
  #             only: release
  #     - terraform-apply-staging:
  #         requires:
  #           - terraform-compliance-staging
  #         filters:
  #           branches:
  #             only: release
  #     - deploy-to-staging:
  #         context:
  #           - api-nuget-token-context
  #           - "Serverless Framework"
  #         requires:
  #           - terraform-apply-staging
  #         filters:
  #           branches:
  #             only: release
  #     - permit-production-terraform-release:
  #         type: approval
  #         requires:
  #           - deploy-to-staging
  #     - assume-role-production:
  #         context: api-assume-role-housing-production-context
  #         requires:
  #             - permit-production-terraform-release
  #         filters:
  #            branches:
  #              only: release
  #     - terraform-init-and-plan-production:
  #         requires:
  #           - assume-role-production
  #         filters:
  #           branches:
  #             only: release
  #     - terraform-compliance-production:
  #         requires:
  #           - terraform-init-and-plan-production
  #         filters:
  #           branches:
  #             only: release
  #     - terraform-apply-production:
  #         requires:
  #           - terraform-compliance-production
  #         filters:
  #           branches:
  #             only: release
  #     - permit-production-release:
  #         type: approval
  #         requires:
  #           - terraform-apply-production
  #         filters:
  #           branches:
  #             only: release
  #     - deploy-to-production:
  #         context:
  #           - api-nuget-token-context
  #           - "Serverless Framework"
  #         requires:
  #           - permit-production-release
  #         filters:
  #           branches:
  #             only: release

  deploy-terraform-pre-production:
    jobs:
      - permit-pre-production-terraform-workflow:
          type: approval
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - assume-role-pre-production:
          context: api-assume-role-housing-pre-production-context
          requires:
            - permit-pre-production-terraform-workflow
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - terraform-init-and-plan-pre-production:
          requires:
            - assume-role-pre-production
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - terraform-compliance-pre-production:
          requires:
            - terraform-init-and-plan-pre-production
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - permit-pre-production-terraform-deployment:
          type: approval
          requires:
            - terraform-compliance-pre-production
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - terraform-apply-pre-production:
          requires:
            - permit-pre-production-terraform-deployment
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows

  deploy-code-pre-production:
    jobs:
      - permit-pre-production-code-workflow:
          type: approval
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - build-and-test:
          requires:
            - permit-pre-production-code-workflow
          context: 
            - api-nuget-token-context
            - SonarCloud
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - assume-role-pre-production:
          context: api-assume-role-housing-pre-production-context
          requires:
            - build-and-test
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows
      - deploy-to-pre-production:
          context:
          - api-nuget-token-context
          - "Serverless Framework"
          requires:
            - assume-role-pre-production        
          filters:
            branches:
              only: ts-2045-add-pre-production-workflows